# Generated by Django 4.0.4 on 2022-05-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customer_country_customer_postelcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='title',
            new_name='name',
        ),
    ]
