# Generated by Django 4.0.4 on 2022-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_title_services_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Actual_price',
        ),
        migrations.RemoveField(
            model_name='services',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='services',
            name='mobile_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='services',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
