# Generated by Django 4.0.4 on 2022-05-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_services_expenditure_price_services_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='mobile_no',
            field=models.IntegerField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='services',
            name='phone_no',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
