# Generated by Django 4.0.4 on 2022-05-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_services_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='city',
            field=models.CharField(default='abc', max_length=200),
        ),
    ]
