# Generated by Django 4.0.4 on 2022-05-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_services_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='as_per',
        ),
        migrations.AddField(
            model_name='services',
            name='Province',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Islamabad Capital Territory', 'Islamabad Capital Territory'), ('Balochistan', 'Balochistan')], default='abc', max_length=56),
        ),
    ]
