# Generated by Django 4.0.4 on 2022-05-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_services_cnic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='Shop_References',
        ),
    ]
