# Generated by Django 4.0.4 on 2022-05-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_description_services_shop_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='Service_image2',
        ),
    ]
