# Generated by Django 4.0.4 on 2022-05-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='document',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Addvance_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Remaing_Bill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='Total_Bill',
            field=models.IntegerField(default=0),
        ),
    ]
