# Generated by Django 4.0.4 on 2022-05-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_orderplaced_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Addvance_payment',
            new_name='Advance_payment',
        ),
    ]
