# Generated by Django 4.0.4 on 2022-05-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_addvance_payment_orderplaced_advance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='Bill_status',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=100),
        ),
    ]
