# Generated by Django 4.0.4 on 2022-05-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_orderplaced_bill_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit',
            name='expencess',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='service',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='user',
        ),
        migrations.DeleteModel(
            name='expence',
        ),
        migrations.DeleteModel(
            name='profit',
        ),
    ]
