# Generated by Django 4.0.4 on 2022-05-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_about_us_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='quantity',
        ),
    ]
