# Generated by Django 4.0.4 on 2022-05-29 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_cart_customer_remove_contact_us_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=70, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only a whole number are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only a whole number are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postelcode',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]+{5}$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='whatsapp_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only a whole number are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='Cnic',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[0-9]+{13}$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='Employee',
            field=models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Sweaper', 'Sweaper'), ('Carpenter', 'Carpenter'), ('Drain clean', 'Drain clean'), ('AC repair', 'AC repair'), ('Painting & Decorating', 'Painting & Decorating')], default='Plumber', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='Province',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Islamabad Capital Territory', 'Islamabad Capital Territory'), ('Balochistan', 'Balochistan')], default='Punjab', max_length=56),
        ),
        migrations.AlterField(
            model_name='services',
            name='city',
            field=models.CharField(max_length=70, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='mobile_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only a whole number are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='phone_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only a whole number are allowed.')]),
        ),
    ]
