# Generated by Django 4.0.4 on 2022-05-29 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_customer_city_alter_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Cnic',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{13}$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=70, validators=[django.core.validators.RegexValidator('^[a-zA-Z]$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]$', 'Only a whole number are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]$', 'Only a whole number are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postelcode',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='whatsapp_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]$', 'Only a whole number are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='Cnic',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[0-9]{13}$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='city',
            field=models.CharField(max_length=70, validators=[django.core.validators.RegexValidator('^[a-zA-Z]$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='mobile_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]$', 'Only a whole number are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='phone_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]$', 'Only a whole number are allowed.')]),
        ),
    ]
