# Generated by Django 4.0.4 on 2022-05-29 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_customer_city_alter_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z" "a-zA-Z]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z" "a-zA-Z]*$', 'Only alphabets are allowed.')]),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z" "a-zA-Z]*$', 'Only alphabets are allowed.')]),
        ),
    ]
