# Generated by Django 4.0.4 on 2022-05-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_orderplaced_statuscus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='ratting',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Service is Start', 'Service is Start'), ('Service is Complete', 'Service is Complete'), ('Cancel', 'Cancel')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='statuscus',
            field=models.CharField(choices=[('Service is Completed', 'Service is Completed'), ('Service is not  Completed', 'Service is not Completed')], default='In progress', max_length=100),
        ),
    ]
